version: '3.4'
services:
  lulc:
    image: developmentseed/lulc:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $HOME/.aws:/root/.aws
      - $PWD/:/app
    environment:
      - AWS_PROFILE=devseed
    ports:
      - '8888:8888'
